### PR TITLE
fix shifting in encoding

### PR DESCRIPTION
**Pull request by vtolstov**
@aaronlehmann fix from #2 

Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by vtolstov** [comment]
@mitchellh ping..
Also do you have some code for server part?

**Comment by mitchellh** [comment]
Thanks! And no, I never did a server since I only required the client.

**Comment by vtolstov** [comment]
@mitchellh if i complete server part, does it possible to integrate it to packer, because now - if i connect to vnc and packer doing boot_command, connection closed, but if vnc package have server part, we simple can write proxy, so packer and user connects to it in the same time...  and connection not dropped anymore.

**Comment by mitchellh** [comment]
Thats an interesting idea. I would at the least merge it here, but we should have a longer discusison about Packer.

**Pull request merged**
